### ISSUE TITLE
Abertura do projeto

### ISSUE THREAD

**Issue by rodrigovcortezi** [rodrigovcortezi/puc-aulas#1]
Issue criada para discutir as idéias do projeto, bem como identificar os problemas e suas oportunidades e possíveis soluções.

**Comment by rodrigovcortezi** [comment]
@danielcr10 acho que sim. Os dados na simulação e no microhorário vem do mesmo lugar. Se a gente achar que vale a pena pegar da simulação, depois podemos avançar isso. Mas acho que pra começar, pegar do microhorário ta tranquilo.

**Comment by danielcr10** [comment]
Fechou negow!!
 O que a gente teria que definir agora?
Tu podia só fazer aquelas configs de repositório pra fazer uma parada organizada hein, que acha?

**Comment by rodrigovcortezi** [comment]
@danielcr10 agora é decidir o que vamos usar para implementar a aplicação. Não precisamos pensar em tudo logo de cara, mas acho que é válido pelo menos ter em mente o seguinte:

- As linguagens de programação.
- O servidor da aplicação. (Back-end)
- O banco de dados. (DB)
- O framework javascript (Front-end)
- A biblioteca/framework de design (CSS)

**Comment by rodrigovcortezi** [comment]
Acho que podemos usar o [Feathers](https://docs.feathersjs.com/) (Back-end), PostgreSQL (DB), [Vue](https://vuejs.org/) (Front-end) e [Tailwind](https://tailwindcss.com/) (CSS). O que tu acha?

**Comment by danielcr10** [comment]
Tá show nego. Mas você não acha legal levantar as funcionalidades iniciais/básicas pra dar pelo menos um norte? Só uma lista

**Comment by danielcr10** [comment]
@rodrigovcortezi Acho que eu to fudido. Nunca ouvi falar nesse do Back, o css já ouvi falar uma vez, mas não faço ideia tbm, mas imagino que tu tem razão pra escolha, então vamos.

**Comment by danielcr10** [comment]
Pensando nas possíveis funcionalidades imaginei a seguinte estrutura por matéria. Para guiar na hora de extrair os dados. O que tu acha?

_Informações necessárias de cada matéria:_
- Código da disciplina
- Nome da disciplina
- Horário e dia da semana
- Créditos
- Tem pre-requisito
- Lista pre-requisitos

**Comment by danielcr10** [comment]
Andei pensando em algumas coisas hoje e vou registrar só pra não esquecer. 
A ideia é fazer um simulador de matrícula que vai ficar disponível, mas acho que podemos fazer algumas mudanças também. Uma das que pensei seria poder registrar duas disciplinas no mesmo dia e horário, porem com cores diferentes. Para que seja possível identificar visualmente.
A ideia é possibilitar opções de matrícula caso não tenha vaga para aquela determinada matéria, já tendo assim uma opção ou até um conjunto de opção. Fazendo cada conjunto de opção de uma cor. 

### Uma ideia visual tosca:
<img width="545" alt="Pequeno exemplo" src="https://user-images.githubusercontent.com/11623016/65463984-36755880-de2f-11e9-8f30-191b502ace68.png">

**Comment by rodrigovcortezi** [comment]
@danielcr10 Muito boa idéia! Acho que podemos amadurecer isso aí.
De qual forma, acho que já temos uma bom princípio de partida para começarmos.. Portanto, vou fechar essa issue.
